#!/usr/bin/env bash
if [ "$1" == "" ] || [ "$2" == "" ]; then
    echo "RazorRun <list of input files> <analyzer name> <options>"
else
   runner="${CMSSW_BASE}/src/run3_llp_analyzer/bin/Run$2"
   if [ ! -x "${runner}" ]; then
      echo "Missing analyzer runner: ${runner}"
      exit 1
   fi

   echo $1 $2
    "${runner}" "$1" "${@:3}"
fi
